version: 2
updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: monthly
      time: "05:00"
      timezone: Asia/Shanghai
    ignore:
      - dependency-name: semantic-release
        versions:
          - ">= 21.0.1"
