version: 2
updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: "monthly"
      time: "04:00"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: semantic-release
        versions:
          - ">= 21.0.1"
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: "monthly"
      time: "04:00"
      timezone: Asia/Shanghai
